version: "3.1"

services:
  cron-telebot:
    build:
      context: .
      dockerfile: Dockerfile.main
    command: python main.py
    restart: always
    env_file: .env
    depends_on:
      - wait-dependencies
    ports:
      - "8000:8000"
  flask:
    build:
      context: .
      dockerfile: Dockerfile.api
    links:
      - mongo
    command: python api.py
    restart: always
    env_file: .env
    depends_on:
      - wait-dependencies
    ports:
      - "5000:5000"
  mongo:
    image: mongo
    restart: always
    env_file: .env
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
  wait-dependencies:
    image: willwill/wait-for-it:latest
    depends_on:
      - mongo
    entrypoint: /bin/sh
    command: >
      -c "./wait-for-it.sh mongo:27017 --strict --timeout=1"
  # If database debugging is needed
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #   depends_on:
  #     - mongo
volumes:
  dbdata:
